openapi: 3.0.0
info:
  version: '1.0'
  title: 'Wallet to Wallet'
  description: 'The following API documentation describes the Wallet to wallet service.'
servers:
  - url: 'https://[base_url]'
paths:
  /payment/send/toAma:
    post:
      description: "ISSUER WALLET/MOBILE MANAGER TO AMA"
      summary: 'ISSUER WALLET/MOBILE MANAGER TO AMA'
      operationId: w2wTo
      tags:
        - w2w
      requestBody:
          required: true
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/paymentBO'
      responses:
        '200':
          description: 'Sample response: Details about AMA Serices response'
          headers:
            Content-Type:
              description: application/json
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentBORsFromAma'
        '400':
          description: If a problem occurs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /payment/send/fromAma:
    post:
      description: "AMA TO DESTINATION WALLET/MOBILE MANAGER"
      summary: 'AMA TO DESTINATION WALLET/MOBILE MANAGER'
      operationId: w2wFrom
      tags:
        - w2w
      requestBody:
          required: true
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/paymentBOFrom'
      responses:
        '200':
          description: 'Sample response: Details about AMA Serices response'
          headers:
            Content-Type:
              description: application/json
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentBORsToAma'
        '400':
          description: If a problem occurs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /payment/update/toAma:
    post:
      description: "ACQUIRER TO AMA NOTIFICATION"
      summary: 'ACQUIRER TO AMA NOTIFICATION'
      operationId: w2wUTo
      tags:
        - w2w
      requestBody:
          required: true
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/paymentBOUpdateTo'
      responses:
        '200':
          description: 'Sample response: Details about AMA Serices response'

  /payment/update/fromAma:
    post:
      description: "AMA TO ISSUER NOTIFICATION"
      summary: 'AMA TO ISSUER NOTIFICATION'
      operationId: w2wUFrom
      tags:
        - w2w
      requestBody:
          required: true
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/paymentBOUpdateFrom'
      responses:
        '400':
          description: If a problem occurs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    paymentBO:
      type: object      
      required:
          - intent
          - createtime
          - amount
          - currency
          - walletsource
          - tomember
          - walletdestination
      properties:
        intent:
          type: string
          description: 'Identifies the transaction type, must be = mobile_transfer'
          example: 'mobile_transfer'
        description:
          type: string
          description: 'Transaction description'
          example: 'Sample transaction description'
        createtime:
          type: integer
          description: 'Transaction creation date and time expressed in number of milliseconds since 01/01/1970'
          example: 1490109044
        amount:
          type: integer
          description: 'Transaction amount'
          example: 5000
        currency:
          type: integer
          description: 'Transaction currency ISO code'
          example: 426
        validityduration:
          type: integer
          description: 'Validity duration of the transaction waiting for decision, if not set or set to a value <=0, the transaction will wait indefinitely. Validity duration is expressed in seconds'
          example: '18000'
        issuertrxref:
          type: string
          description: 'Unique identifier of the transaction, generated by the issuer'
          example: 'MTNCI945215625942016'
        walletsource:
          type: string
          description: 'Source wallet identifier'
          example: 'CBL'
        tomember:
            type: string
            description: 'Destination wallet manager. If not present the tomember will be recovered from the alias proxy server'
            example: 'MNO_1'
        walletdestination:
          type: string
          description: 'Destination wallet identifier or destination wallet Alias'
          example: 'PayLogic'
    paymentBOUpdateTo:
      type: object      
      required:
          - intent
          - issuertrxref
          - updatetime
          - state
          - vouchercode
      properties:
        intent:
          type: string
          description: 'Same as original transaction'
          example: 'mobile_transfer'
        updatetime:
          type: integer
          description: 'Transaction update date and time expressed in number of milliseconds since 01/01/1970'
          example: 1490109044
        vouchercode:
          type: string
          description: 'A Unique voucher for the transaction'
          example: 'AB345EF89012'
        state:
          type: string
          description: 'Describe the result of the transaction. Possible values are [REJECTED, ACCEPTED]'
          example: 'ACCEPTED'
        issuertrxref:
          type: string
          description: 'Same as original transaction'
          example: 'MTNCI945215625942016'
        acquirertrxref:
            type: string
            description: 'Same as original transaction'
            example: 'ACQCI945215625942016'
    paymentBOUpdateFrom:
      type: object      
      required:
          - intent
          - issuertrxref
          - updatetime
          - state
          - vouchercode
      properties:
        intent:
          type: string
          description: 'Same as original transaction'
          example: 'mobile_transfer'
        updatetime:
          type: integer
          description: 'Transaction update date and time expressed in number of milliseconds since 01/01/1970'
          example: 1490109044
        vouchercode:
          type: string
          description: 'A Unique voucher for the transaction'
          example: 'AB345EF89012'
        state:
          type: string
          description: 'Describe the result of the transaction. Possible values are [REJECTED, ACCEPTED, PENDING, CANCELLED]'
          example: 'ACCEPTED'
        issuertrxref:
          type: string
          description: 'Same as original transaction'
          example: 'MTNCI945215625942016'
        acquirertrxref:
            type: string
            description: 'Same as original transaction'
            example: 'ACQCI945215625942016'
    paymentBOFrom:
      type: object      
      required:
          - intent
          - createtime
          - amount
          - currency
          - walletsource
          - fromMember
          - vouchercode
          - walletdestination
      properties:
        intent:
          type: string
          description: 'Identifies the transaction type, must be = mobile_transfer'
          example: 'mobile_transfer'
        description:
          type: string
          description: 'Transaction description'
          example: 'Sample transaction description'
        createtime:
          type: integer
          description: 'Transaction creation date and time expressed in number of milliseconds since 01/01/1970'
          example: 1490109044
        vouchercode:
            type: string
            description: 'A Unique voucher for the transaction'
            example: 'AB345EF89012'
        amount:
          type: integer
          description: 'Transaction amount'
          example: 5000
        currency:
          type: integer
          description: 'Transaction currency ISO code'
          example: 426
        expirytime:
          type: integer
          description: 'Voucher expiry date and time expressed in number of milliseconds since 01/01/1970'
          example: 1800086522
        frommember:
            type: string
            description: 'Source wallet manager'
            example: 'MNO_2'
        issuertrxref:
          type: string
          description: 'Unique identifier of the transaction, generated by the issuer'
          example: 'MTNCI945215625942016'
        walletsource:
          type: string
          description: 'Source wallet identifier'
          example: 'CBL'
        walletdestination:
          type: string
          description: 'Destination wallet identifier or destination wallet Alias'
          example: 'PayLogic'
    Error:
      type: object
      required:
        - error
        - error_description
      properties:
        error:
          type: string
          example: invalid_grant
        error_description:
          type: string
          example: Bad credentials
    paymentBORsToAma:
      type: object      
      required:
          - state
          - acquirertrxref
      properties:
        state:
          type: string
          description: 'Describe the result of the transaction. Possible values are [ACCEPTED, PENDING]'
          example: 'ACCEPTED'
        acquirertrxref:
            type: string
            description: 'The acquirer transaction reference'
            example: 'ACQCI945215625942016'
    paymentBORsFromAma:
      type: object      
      required:
          - state
          - acquirertrxref
      properties:
        expirytime:
          type: integer
          description: 'Voucher expiry date and time expressed in number of milliseconds since 01/01/1970, present if the state is PENDING'
          example: 1800086522
        state:
          type: string
          description: 'Describe the result of the transaction. Possible values are [ACCEPTED, PENDING]'
          example: 'ACCEPTED'
        acquirertrxref:
            type: string
            description: 'The acquirer transaction reference'
            example: 'ACQCI945215625942016'
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []
